import { Product, Category, ProductReview } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'all',
    nameEn: 'All Items',
    nameBn: 'সব পণ্য',
    icon: 'Grid',
    color: 'from-emerald-500 to-teal-600'
  },
  {
    id: 'vegetables-fruits',
    nameEn: 'Vegetables & Fruits',
    nameBn: 'শাকসবজি ও ফলমূল',
    icon: 'Apple',
    color: 'from-green-500 to-emerald-600'
  },
  {
    id: 'fish-meat',
    nameEn: 'Chicken, Meat & Fish',
    nameBn: 'মুরগি, মাংস ও মাছ',
    icon: 'Fish',
    color: 'from-rose-500 to-red-600'
  },
  {
    id: 'dairy-bread-eggs',
    nameEn: 'Dairy, Bread & Eggs',
    nameBn: 'দুগ্ধজাত ও ডিম',
    icon: 'Cookie',
    color: 'from-amber-400 to-orange-500'
  },
  {
    id: 'snacks-munchies',
    nameEn: 'Snacks & Munchies',
    nameBn: 'স্ন্যাক্স ও চিপস',
    icon: 'Dessert',
    color: 'from-red-400 to-pink-500'
  },
  {
    id: 'cold-drinks',
    nameEn: 'Drinks & Juices',
    nameBn: 'ঠান্ডা পানীয় ও জুস',
    icon: 'CupSoda',
    color: 'from-cyan-400 to-blue-500'
  },
  {
    id: 'staples',
    nameEn: 'Atta, Rice & Dal',
    nameBn: 'আটা, চাল ও ডাল',
    icon: 'Wheat',
    color: 'from-yellow-500 to-amber-600'
  },
  {
    id: 'personal-care',
    nameEn: 'Personal Care',
    nameBn: 'ব্যক্তিগত যত্ন',
    icon: 'Sparkles',
    color: 'from-purple-400 to-indigo-500'
  },
  {
    id: 'masala-oil-more',
    nameEn: 'Masala, Oil & More',
    nameBn: 'মসলা, তেল ও অনন্য',
    icon: 'Flame',
    color: 'from-orange-500 to-amber-600'
  },
  {
    id: 'organic-health',
    nameEn: 'Organic & Healthy Living',
    nameBn: 'অর্গানিক ও স্বাস্থ্যকর খাদ্য',
    icon: 'Leaf',
    color: 'from-emerald-400 to-emerald-700'
  },
  {
    id: 'pet-care',
    nameEn: 'Pet Care',
    nameBn: 'পোষা প্রাণীর যত্ন',
    icon: 'PawPrint',
    color: 'from-blue-400 to-indigo-600'
  },
  {
    id: 'household',
    nameEn: 'Household',
    nameBn: 'গৃহস্থালী সামগ্রী',
    icon: 'Home',
    color: 'from-slate-400 to-slate-600'
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'p_rui_fish',
    nameEn: 'Fresh Rui Fish (Cleaned & Cut)',
    nameBn: 'তাজা রুই মাছ (কাটা ও পরিষ্কার করা)',
    category: 'fish-meat',
    price: 380,
    discountPrice: 340,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&q=80&w=400',
    stock: 15,
    isVeg: false
  },
  {
    id: 'p_beef_bone',
    nameEn: 'Premium Beef Bone-In (Fresh Bazaar)',
    nameBn: 'প্রিমিয়াম গরুর মাংস (হাড়সহ)',
    category: 'fish-meat',
    price: 780,
    discountPrice: 750,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=400',
    stock: 20,
    isVeg: false
  },
  {
    id: 'p_chicken',
    nameEn: 'Fresh Broiler Chicken (Clean Cut)',
    nameBn: 'তাজা ব্রয়লার মুরগির মাংস',
    category: 'fish-meat',
    price: 210,
    discountPrice: 195,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&q=80&w=400',
    stock: 30,
    isVeg: false
  },
  {
    id: 'p_mustard_oil',
    nameEn: 'Pure Mustard Oil (Ghani Broken)',
    nameBn: 'খাটি সরিষার তেল (ঘানি ভাঙ্গা)',
    category: 'masala-oil-more',
    price: 240,
    discountPrice: 225,
    unitEn: '1 L',
    unitBn: '১ লিটার',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=400',
    stock: 12,
    isVeg: true
  },
  {
    id: 'p_turmeric_powder',
    nameEn: 'Radhuni Turmeric Powder',
    nameBn: 'রাধুনী হলুদ গুঁড়ো',
    category: 'masala-oil-more',
    price: 110,
    discountPrice: 100,
    unitEn: '200 g',
    unitBn: '২০০ গ্রাম',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=400',
    stock: 18,
    isVeg: true
  },
  {
    id: 'p_sundarban_honey',
    nameEn: 'Organic Sundarban Honey',
    nameBn: 'সুন্দরবনের প্রাকৃতিক মধু (অর্গানিক)',
    category: 'organic-health',
    price: 450,
    discountPrice: 420,
    unitEn: '500 g',
    unitBn: '৫০০ গ্রাম',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=400',
    stock: 8,
    isVeg: true
  },
  {
    id: 'p_chia_seeds',
    nameEn: 'Premium Organic Chia Seeds',
    nameBn: 'অর্গানিক চিয়া সীড প্রিমিয়াম',
    category: 'organic-health',
    price: 290,
    discountPrice: 260,
    unitEn: '250 g',
    unitBn: '২৫০ গ্রাম',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1590004953392-5aba2e72269a?auto=format&fit=crop&q=80&w=400',
    stock: 15,
    isVeg: true
  },
  {
    id: 'p_dog_food',
    nameEn: 'SmartHeart Dry Dog Food',
    nameBn: 'স্মার্টহার্ট ড্রাই ডগ ফুড',
    category: 'pet-care',
    price: 340,
    discountPrice: 310,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&q=80&w=400',
    stock: 10,
    isVeg: false
  },
  {
    id: 'p_cat_food',
    nameEn: 'Whiskas Ocean Fish Cat Food',
    nameBn: 'হুইস্কাস ওশেন ফিশ ক্যাট ফুড',
    category: 'pet-care',
    price: 180,
    discountPrice: 165,
    unitEn: '400 g',
    unitBn: '৪০০ গ্রাম',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?auto=format&fit=crop&q=80&w=400',
    stock: 25,
    isVeg: false
  },
  {
    id: 'p1',
    nameEn: 'Fresh Red Tomato',
    nameBn: 'দেশি লাল টমেটো',
    category: 'vegetables-fruits',
    price: 45,
    discountPrice: 38,
    unitEn: '500 g',
    unitBn: '৫০০ গ্রাম',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=400',
    stock: 25,
    isVeg: true
  },
  {
    id: 'p2',
    nameEn: 'Fresh Green Chili',
    nameBn: 'কাঁচা মরিচ',
    category: 'vegetables-fruits',
    price: 25,
    unitEn: '150 g',
    unitBn: '১৫০ গ্রাম',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119cb6aa?auto=format&fit=crop&q=80&w=400',
    stock: 50,
    isVeg: true
  },
  {
    id: 'p3',
    nameEn: 'Fresh Baby Potatoes',
    nameBn: 'নতুন আলু',
    category: 'vegetables-fruits',
    price: 52,
    discountPrice: 48,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=400',
    stock: 40,
    isVeg: true
  },
  {
    id: 'p4',
    nameEn: 'Premium Sabri Banana',
    nameBn: 'সবরি কলা (হালি)',
    category: 'vegetables-fruits',
    price: 40,
    unitEn: '4 pcs',
    unitBn: '৪ পিস',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=400',
    stock: 15,
    isVeg: true
  },
  {
    id: 'p5',
    nameEn: 'Fresh Farm Eggs',
    nameBn: 'ফার্মের লাল ডিম',
    category: 'dairy-bread-eggs',
    price: 55,
    discountPrice: 52,
    unitEn: '4 pcs',
    unitBn: '৪ পিস',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&q=80&w=400',
    stock: 120,
    isVeg: false
  },
  {
    id: 'p6',
    nameEn: 'Liquid Milk (Aarong)',
    nameBn: 'তরল দুধ (আড়ং)',
    category: 'dairy-bread-eggs',
    price: 95,
    unitEn: '1 L',
    unitBn: '১ লিটার',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&q=80&w=400',
    stock: 35,
    isVeg: true
  },
  {
    id: 'p7',
    nameEn: 'Amul Salted Butter',
    nameBn: 'নোনতা মাখন (Amul)',
    category: 'dairy-bread-eggs',
    price: 270,
    discountPrice: 245,
    unitEn: '200 g',
    unitBn: '২০০ গ্রাম',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=400',
    stock: 18,
    isVeg: true
  },
  {
    id: 'p8',
    nameEn: 'Fresh Premium White Bread',
    nameBn: 'স্লাইসড পাউরুটি',
    category: 'dairy-bread-eggs',
    price: 65,
    unitEn: '400 g',
    unitBn: '৪০০ গ্রাম',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
    stock: 30,
    isVeg: true
  },
  {
    id: 'p9',
    nameEn: 'Lays Potato Chips (India)',
    nameBn: 'লেইস পটেটো চিপস',
    category: 'snacks-munchies',
    price: 70,
    unitEn: '50 g',
    unitBn: '৫০ গ্রাম',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d22?auto=format&fit=crop&q=80&w=400',
    stock: 80,
    isVeg: true
  },
  {
    id: 'p10',
    nameEn: 'Premium Salted Cashews',
    nameBn: 'প্রিমিয়াম কাজুবাদাম',
    category: 'snacks-munchies',
    price: 240,
    discountPrice: 210,
    unitEn: '150 g',
    unitBn: '১৫০ গ্রাম',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&q=80&w=400',
    stock: 25,
    isVeg: true
  },
  {
    id: 'p11',
    nameEn: 'Coca-Cola Bottle',
    nameBn: 'কোকা-কোলা বোতল',
    category: 'cold-drinks',
    price: 45,
    unitEn: '500 ml',
    unitBn: '৫০০ মিলি',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    stock: 150,
    isVeg: true
  },
  {
    id: 'p12',
    nameEn: 'Fresh Pulp Orange Juice',
    nameBn: 'তাজা কমলার রস',
    category: 'cold-drinks',
    price: 180,
    discountPrice: 155,
    unitEn: '1 L',
    unitBn: '১ লিটার',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=400',
    stock: 45,
    isVeg: true
  },
  {
    id: 'p13',
    nameEn: 'Miniket Rice Premium',
    nameBn: 'মিনিকেট চাল প্রিমিয়াম',
    category: 'staples',
    price: 400,
    discountPrice: 375,
    unitEn: '5 kg',
    unitBn: '৫ কেজি',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400',
    stock: 60,
    isVeg: true
  },
  {
    id: 'p14',
    nameEn: 'Premium Masoor Dal',
    nameBn: 'দেশি মসুর ডাল',
    category: 'staples',
    price: 140,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1547058881-aa0edd92aab3?auto=format&fit=crop&q=80&w=400',
    stock: 100,
    isVeg: true
  },
  {
    id: 'p15',
    nameEn: 'Savlon Antiseptic Soap',
    nameBn: 'স্যাভলন সাবান',
    category: 'personal-care',
    price: 75,
    unitEn: '125 g',
    unitBn: '১২৫ গ্রাম',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1607006342411-10d3ab4b8782?auto=format&fit=crop&q=80&w=400',
    stock: 65,
    isVeg: true
  },
  {
    id: 'p16',
    nameEn: 'Vim Dishwash Liquid',
    nameBn: 'ভিম লিকুইড ক্লিনার',
    category: 'household',
    price: 125,
    discountPrice: 110,
    unitEn: '500 ml',
    unitBn: '৫০০ মিলি',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1607006342411-10d3ab4b8782?auto=format&fit=crop&q=80&w=400', // standard clean aesthetic
    stock: 45,
    isVeg: true
  },
  {
    id: 'p17',
    nameEn: 'Fresh Green Cucumber',
    nameBn: 'দেশি শসা (তাজা)',
    category: 'vegetables-fruits',
    price: 60,
    discountPrice: 48,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&q=80&w=400',
    stock: 35,
    isVeg: true
  },
  {
    id: 'p18',
    nameEn: 'Fresh Cauliflower',
    nameBn: 'তাজা ফুলকপি (পিস)',
    category: 'vegetables-fruits',
    price: 45,
    unitEn: '1 pc',
    unitBn: '১ পিস',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ecf?auto=format&fit=crop&q=80&w=400',
    stock: 25,
    isVeg: true
  },
  {
    id: 'p19',
    nameEn: 'Padma River Ilish Fish',
    nameBn: 'পদ্মার তাজা ইলিশ মাছ (বড়)',
    category: 'fish-meat',
    price: 1450,
    discountPrice: 1350,
    unitEn: '1 kg (approx)',
    unitBn: '১ কেজি প্রায়',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&q=80&w=400',
    stock: 12,
    isVeg: false
  },
  {
    id: 'p20',
    nameEn: 'Premium Mutton (Khashi)',
    nameBn: 'খাসির তাজা মাংস (প্রিমিয়াম)',
    category: 'fish-meat',
    price: 1100,
    discountPrice: 1050,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=400',
    stock: 15,
    isVeg: false
  },
  {
    id: 'p21',
    nameEn: 'Aarong Premium Sweet Yogurt (Meethi Doi)',
    nameBn: 'আড়ং মিষ্টি দই',
    category: 'dairy-bread-eggs',
    price: 140,
    discountPrice: 130,
    unitEn: '500 g',
    unitBn: '৫০০ গ্রাম',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=400',
    stock: 40,
    isVeg: true
  },
  {
    id: 'p22',
    nameEn: 'Pran Spicy Chanachur',
    nameBn: 'প্রাণ ঝাল চানাচুর',
    category: 'snacks-munchies',
    price: 85,
    discountPrice: 80,
    unitEn: '300 g',
    unitBn: '৩০০ গ্রাম',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=400',
    stock: 90,
    isVeg: true
  },
  {
    id: 'p23',
    nameEn: 'Oreo Original Chocolate Biscuits',
    nameBn: 'ওরিও চকোলেট বিস্কুট',
    category: 'snacks-munchies',
    price: 45,
    unitEn: '120 g',
    unitBn: '১২০ গ্রাম',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1558961309-dbdf717a13d8?auto=format&fit=crop&q=80&w=400',
    stock: 110,
    isVeg: true
  },
  {
    id: 'p24',
    nameEn: 'Pran Frooto Mango Juice',
    nameBn: 'প্রাণ ফ্রুটো ম্যাঙ্গো জুস',
    category: 'cold-drinks',
    price: 80,
    discountPrice: 75,
    unitEn: '1 L',
    unitBn: '১ লিটার',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1546173159-319807584405?auto=format&fit=crop&q=80&w=400',
    stock: 75,
    isVeg: true
  },
  {
    id: 'p25',
    nameEn: 'Sprite Lemon-Lime Drink',
    nameBn: 'স্প্রাইট কোল্ড ড্রিংক',
    category: 'cold-drinks',
    price: 70,
    unitEn: '1.25 L',
    unitBn: '১.২৫ লিটার',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    stock: 100,
    isVeg: true
  },
  {
    id: 'p26',
    nameEn: 'Bashundhara Fortified Atta (Maida)',
    nameBn: 'বসুন্ধরা আটা (প্যাকেট)',
    category: 'staples',
    price: 135,
    discountPrice: 128,
    unitEn: '2 kg',
    unitBn: '২ কেজি',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?auto=format&fit=crop&q=80&w=400',
    stock: 55,
    isVeg: true
  },
  {
    id: 'p27',
    nameEn: 'Premium Chinigura Sugandhi Rice',
    nameBn: 'চিনিগুড়া সুগন্ধি চাল',
    category: 'staples',
    price: 165,
    discountPrice: 155,
    unitEn: '1 kg',
    unitBn: '১ কেজি',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400',
    stock: 80,
    isVeg: true
  },
  {
    id: 'p28',
    nameEn: 'Sunsilk Black Shine Shampoo',
    nameBn: 'সানসিল্ক শ্যাম্পু ব্ল্যাক শাইন',
    category: 'personal-care',
    price: 220,
    discountPrice: 205,
    unitEn: '180 ml',
    unitBn: '১৮০ মিলি',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&q=80&w=400',
    stock: 45,
    isVeg: true
  },
  {
    id: 'p29',
    nameEn: 'Colgate Strong Teeth Toothpaste',
    nameBn: 'কোলগেট টুথপেস্ট',
    category: 'personal-care',
    price: 130,
    unitEn: '150 g',
    unitBn: '১৫০ গ্রাম',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&q=80&w=400',
    stock: 60,
    isVeg: true
  },
  {
    id: 'p30',
    nameEn: 'Radhuni Red Chili Powder',
    nameBn: 'রাধুনী মরিচ গুঁড়ো',
    category: 'masala-oil-more',
    price: 130,
    discountPrice: 120,
    unitEn: '200 g',
    unitBn: '২০০ গ্রাম',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=400',
    stock: 30,
    isVeg: true
  },
  {
    id: 'p31',
    nameEn: 'Rupchanda Fortified Soyabean Oil',
    nameBn: 'রূপচাঁদা সয়াবিন তেল',
    category: 'masala-oil-more',
    price: 840,
    discountPrice: 815,
    unitEn: '5 L',
    unitBn: '৫ লিটার',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=400',
    stock: 25,
    isVeg: true
  },
  {
    id: 'p32',
    nameEn: 'Organic Ispahani Green Tea',
    nameBn: 'ইস্পাহানি অর্গানিক গ্রিন টি',
    category: 'organic-health',
    price: 185,
    discountPrice: 170,
    unitEn: '50 Bags',
    unitBn: '৫০ ব্যাগ',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=400',
    stock: 20,
    isVeg: true
  },
  {
    id: 'p33',
    nameEn: 'Whiskas Wet Cat Food Gravy Salmon',
    nameBn: 'হুইস্কাস ক্যাট ফুড গ্রেভি স্যামন',
    category: 'pet-care',
    price: 85,
    unitEn: '85 g',
    unitBn: '৮৫ গ্রাম',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?auto=format&fit=crop&q=80&w=400',
    stock: 50,
    isVeg: false
  },
  {
    id: 'p34',
    nameEn: 'Harpic Active Fresh Toilet Cleaner',
    nameBn: 'হারপিক টয়লেট ক্লিনার',
    category: 'household',
    price: 175,
    discountPrice: 160,
    unitEn: '750 ml',
    unitBn: '৭৫০ মিলি',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=400',
    stock: 40,
    isVeg: true
  }
];

export const INITIAL_REVIEWS: ProductReview[] = [
  {
    id: 'r1',
    productId: 'p1',
    userName: 'Imrul Hasan',
    rating: 5,
    comment: 'খুবই তাজা ও সুন্দর টমেটো। মাত্র ১০ মিনিটে পেয়েছি, অবিশ্বাস্য!',
    date: '2026-06-20'
  },
  {
    id: 'r2',
    productId: 'p1',
    userName: 'Sarah Kabir',
    rating: 4,
    comment: 'Fresh tomatoes, nicely packed. Will order again from Master Mart.',
    date: '2026-06-21'
  },
  {
    id: 'r3',
    productId: 'p5',
    userName: 'Tanvir Rahman',
    rating: 5,
    comment: 'ডিমগুলো একটাও ভাঙেনি। দারুন প্যাকেজিং ছিল!',
    date: '2026-06-19'
  },
  {
    id: 'r4',
    productId: 'p6',
    userName: 'Nusrat Jahan',
    rating: 5,
    comment: 'Chilled and fresh milk delivered under 10 minutes. Absolute game changer.',
    date: '2026-06-22'
  }
];

export const DICTIONARY = {
  en: {
    appName: 'Master Mart',
    tagline: '10 Minute Superfast Delivery | Hotline: 01613-476659',
    searchPlaceholder: 'Search for milk, tomato, chips or drinks...',
    categoriesHeader: 'Shop by Category',
    allProducts: 'All Products',
    vegTag: 'VEG',
    nonVegTag: 'EGG',
    tk: '৳',
    off: 'OFF',
    deliveryTime: '10 mins',
    addToCart: 'ADD',
    added: 'Added',
    outOfStock: 'Out of Stock',
    reviewsTab: 'Reviews',
    deliveryStatus: 'Delivery Status',
    orderTracking: 'Live Tracking',
    reviewsHeader: 'Customer Reviews',
    addReview: 'Write a Review',
    yourName: 'Your Name',
    ratingLabel: 'Rating',
    commentLabel: 'Comment',
    submitReview: 'Submit Review',
    cartHeader: 'My Cart',
    emptyCart: 'Your cart is empty',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Partner Fee',
    handlingFee: 'Govt Tax & Handling',
    totalAmount: 'Grand Total',
    choosePayment: 'Select Payment Method',
    placeOrder: 'Proceed to Order',
    paymentSuccess: 'Order Successful!',
    paymentProcessing: 'Connecting to Bank Gateway...',
    enterOTP: 'Enter 6-Digit OTP / bKash PIN',
    submitOTP: 'Confirm Transaction',
    trackingProgress: 'Live Tracker Map',
    orderPreparation: 'We are packing your items safely...',
    driverAssigned: 'Rider is on the way to you!',
    eta: 'ETA',
    orderPlaced: 'Order Placed',
    orderPrepared: 'Packed & Dispatched',
    onTheWay: 'Out for Delivery',
    delivered: 'Delivered Successfully!',
    close: 'Close',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    mobileView: 'Mobile View',
    desktopView: 'Desktop View',
    deliveryAddress: 'Delivery from: House 196/4, West Dhanmondi, Dhaka',
    changeAddress: 'Change',
    viewDetails: 'Product Details',
    noProducts: 'No products matches your search.',
    recentOrdersLabel: 'Active Delivery Tracker',
    enterReviewError: 'Please enter a name and comment.',
    bKashWallet: 'bKash Wallet',
    nagadWallet: 'Nagad Wallet',
    creditCard: 'Visa / Mastercard',
    cashOnDelivery: 'Cash on Delivery',
    paymentSimTitle: 'Secure Sandbox Payment Gateway',
    bKashPrompt: 'Enter your 11-digit bKash number to authorize dynamic charge'
  },
  bn: {
    appName: 'মাস্টার মার্ট',
    tagline: '১০ মিনিটে সুপারফাস্ট ডেলিভারি | হটলাইন: 01613-476659',
    searchPlaceholder: 'দুধ, টমেটো, চিপস অথবা জুস খুঁজুন...',
    categoriesHeader: 'ক্যাটাগরি সমূহ',
    allProducts: 'সব পণ্য',
    vegTag: 'নিরামিষ',
    nonVegTag: 'আমিষ/ডিম',
    tk: '৳',
    off: 'ছাড়',
    deliveryTime: '১০ মি.',
    addToCart: 'কিনুন',
    added: 'যুক্ত হয়েছে',
    outOfStock: 'স্টক শেষ',
    reviewsTab: 'রিভিউ সমূহ',
    deliveryStatus: 'ডেলিভারি অবস্থা',
    orderTracking: 'লাইভ ট্র্যাকিং',
    reviewsHeader: 'গ্রাহকদের মতামত',
    addReview: 'রিভিউ লিখুন',
    yourName: 'আপনার নাম',
    ratingLabel: 'রেটিং',
    commentLabel: 'মন্তব্য',
    submitReview: 'রিভিউ দিন',
    cartHeader: 'আমার কার্ট',
    emptyCart: 'আপনার কার্ট খালি আছে',
    subtotal: 'পণ্যের মূল্য',
    deliveryFee: 'ডেলিভারি চার্জ',
    handlingFee: 'ট্যাক্স ও হ্যান্ডলিং',
    totalAmount: 'মোট টাকার পরিমাণ',
    choosePayment: 'পেমেন্ট মাধ্যম বেছে নিন',
    placeOrder: 'Proceed to Order',
    paymentSuccess: 'অর্ডার সফল হয়েছে!',
    paymentProcessing: 'ব্যাংক পেমেন্ট গেটওয়ের সাথে সংযুক্ত হচ্ছে...',
    enterOTP: '৬-সংখ্যার ওটিপি / বিকাশ পিন দিন',
    submitOTP: 'লেনদেন নিশ্চিত করুন',
    trackingProgress: 'লাইভ ট্র্যাকার ম্যাপ',
    orderPreparation: 'আপনার পণ্য নিরাপদে প্যাক করা হচ্ছে...',
    driverAssigned: 'ডেলিভারি রাইডার আপনার ঠিকানায় আসছেন!',
    eta: 'পৌঁছানোর সময়',
    orderPlaced: 'অর্ডার নেওয়া হয়েছে',
    orderPrepared: 'প্যাক সম্পন্ন ও রওনা',
    onTheWay: 'রাস্তায় আছে',
    delivered: 'সফলভাবে ডেলিভারি হয়েছে!',
    close: 'বন্ধ করুন',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    mobileView: 'মোবাইল ভিউ',
    desktopView: 'ডেস্কটপ ভিউ',
    deliveryAddress: 'ডেলিভারি ফ্রম: হাউজ ১৯৬/৪, পশ্চিম ধানমন্ডি, ঢাকা',
    changeAddress: 'পরিবর্তন',
    viewDetails: 'পণ্যের বিবরণ',
    noProducts: 'আপনার খোঁজা পণ্যটি পাওয়া যায়নি।',
    recentOrdersLabel: 'চলতি ডেলিভারি ট্র্যাকার',
    enterReviewError: 'দয়া করে নাম এবং মন্তব্য লিখুন।',
    bKashWallet: 'বিকাশ ওয়ালেট',
    nagadWallet: 'নগদ ওয়ালেট',
    creditCard: 'ভিসা / মাস্টারকার্ড',
    cashOnDelivery: 'ক্যাশ অন ডেলিভারি',
    paymentSimTitle: 'নিরাপদ গেটওয়ে সিমুলেশন',
    bKashPrompt: 'পেমেন্ট নিশ্চিত করতে আপনার ১১ ডিজিটের মোবাইল নম্বর দিন'
  }
};
